title: "Pragati's Portfolio"
description: "Data Analyst | Machine Learning | Power BI"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

header_pages:
  - index.md
  - about.md

baseurl: ""
