title: "Pragati's Portfolio"
description: "Data Analyst | Machine Learning | Power BI"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "sunrise"
header_pages:
  - index.md
  - home.md
  - contact.md
  - projects.md
  - about.md
  - certificates.md

baseurl: ""
